=== uy-rrodriguez/uapv-m1-s2/NLTK/nltk_french/xmls/FWI-disaster-project-schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.christophermchurch.com">
  <xs:element name="issue">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="metadata">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="newspaper">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="name"/>
                      <xs:attribute type="xs:date" name="date"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="files">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="file" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="name"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="total"/>
                  <xs:attribute type="xs:string" name="folder"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="notes" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="note" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:byte" name="num" use="optional"/>
							<xs:attribute type="xs:string" name="author" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                 
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="item" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="title" minOccurs="0"/>
              <xs:element type="xs:string" name="byline" minOccurs="0"/>
              <xs:element name="body">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="section" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                          <xs:element type="xs:string" name="heading" minOccurs="0" maxOccurs="1" />
							<xs:element name="para" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType mixed="true">
								   <xs:choice minOccurs="0" maxOccurs="unbounded">
									<xs:element name="sic" type="xs:string"/>
									<xs:element name="illegible">
										<xs:complexType mixed="true">
											<xs:attribute type="xs:byte" name="words"/>
										</xs:complexType>
									</xs:element>
								  </xs:choice>
								  <xs:attribute type="xs:byte" name="num"/>
								</xs:complexType>
							</xs:element>
						    <xs:element name="quote" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType mixed="true">
								  <xs:sequence>
									  <xs:element name="para" maxOccurs="unbounded">
										<xs:complexType mixed="true">
										   <xs:choice minOccurs="0" maxOccurs="unbounded">
											<xs:element name="sic" type="xs:string"/>
											<xs:element name="illegible">
												<xs:complexType mixed="true">
													<xs:attribute type="xs:byte" name="words"/>
												</xs:complexType>
											</xs:element>
										  </xs:choice>
										  <xs:attribute type="xs:byte" name="num"/>
										</xs:complexType>
								      </xs:element>
								  </xs:sequence>
								  <xs:attribute type="xs:string" name="type"/>
							</xs:complexType>
                          </xs:element>
                        </xs:choice>
                        <xs:attribute type="xs:byte" name="num"/>
                      </xs:complexType>
                    </xs:element>            
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="notes" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="note" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:byte" name="num" use="optional"/>
							<xs:attribute type="xs:string" name="author" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="type" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="divers" />
						<xs:enumeration value="ad" />
						<xs:enumeration value="telegram" />
						<xs:enumeration value="article" />
						<xs:enumeration value="letter" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
            <xs:attribute type="xs:string" name="topic" use="optional"/>
            <xs:attribute type="xs:string" name="author" use="optional"/>
            <xs:attribute type="xs:string" name="loc" use="optional"/>
            <xs:attribute type="xs:date" name="date" use="optional"/>
            <xs:attribute type="xs:byte" name="start_page" use="optional"/>
            <xs:attribute type="xs:byte" name="end_page" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== uy-rrodriguez/uapv-m1-s2/NLTK/nltk_french/xmls/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="FWI-disaster-project-style.xsl"?>

<issue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.christophermchurch.com" xsi:schemaLocation="http://www.christophermchurch.com FWI-disaster-project-schema.xsd">
	<metadata>
		<newspaper name="Les Colonies" date="2013-06-09" />
		<files total="02" folder="Les Colonies 1890-1891 NYU">
			<file name="1891-12-20_les-colonies_1.tif"/>
			<file name="1891-12-20_les-colonies_2.tif"/>
		</files>
		<notes>
			<note author="Yvonne Lin" num="01">This article is interesting because ... </note>
			<note author="Yvonne Lin" num="02"></note>
		</notes>
	</metadata>
	
	<item type="telegram" topic="1890 Fire" author="AUTHOR" loc="New York" date="1890-06-17" start_page="01" end_page="02">
		<byline></byline>
		<body>
			<section num="01">
				<heading></heading>
				<para num="01"></para>
			</section>
		</body>
		<notes>
			<note author="Yvonne Lin" num="01">This article is interesting because ... </note>
			<note author="Yvonne Lin" num="02"></note>
		</notes>
	</item>
	<item type="article" topic="1890 Fire" author="AUTHOR" loc="New York" date="1890-06-17" start_page="01" end_page="02">
		<title>test</title>
		<byline>New York, 17 juin</byline>
		<body>
			<section num="01">
				<heading/>
				<para num="01"></para>
				<para num="02"></para>
			</section>
		</body>
		<notes>
			<note author="Yvonne Lin" num="01">This article is interesting because ... </note>
			<note author="Yvonne Lin" num="02"></note>
		</notes>
	</item>
	<item type="divers" topic="1890 Fire" author="AUTHOR" loc="New York" date="1890-06-17" start_page="01" end_page="02">
		<body>
			<section num="01">
				<heading/>
				<para num="01"></para>
				<para num="02"></para>
			</section>
		</body>
		<notes>
			<note author="Yvonne Lin" num="01">This article is interesting because ... </note>
			<note author="Yvonne Lin" num="02"></note>
		</notes>
	</item>
	<item type="letter" topic="1890 Fire" author="AUTHOR" loc="New York" date="1890-06-17" start_page="01" end_page="02">
		<title></title>
		<byline>New York, 17 juin</byline>
		<body>
			<section num="01">
				<heading/>
				<para num="01"></para>
				<para num="02"></para>
			</section>
		</body>
		<notes>
			<note author="Yvonne Lin" num="01">This article is interesting because ... </note>
			<note author="Yvonne Lin" num="02"></note>
		</notes>
	</item>
	<item type="ad" topic="1890 Fire" author="AUTHOR" loc="New York" date="1890-06-17" start_page="01" end_page="02">
		<title></title>
		<byline>New York, 17 juin</byline>
		<body>
			<section num="01">
				<para num="01"></para>
				<para num="02"></para>
			</section>
		</body>
		<notes>
			<note author="Yvonne Lin" num="01">This article is interesting because ... </note>
			<note author="Yvonne Lin" num="02"></note>
		</notes>
	</item>
</issue>
